const data={
        en:{
            select:'Select a package',
            ends:'Ends in #',
            one:'One-off',
            payment:'Select a payment method',
            contact:'Contact us if you have any questions',
            customer:'Customer Service',
            days:"Free %d Days VIP",
            month:"Free %d Month VIP",
            months:"Free %d Months VIP",
            number:"Enter card number",
            card:"Card number",
            pay:"PAY # @",
            selectCard:"Select a card",
            addCard:"Add new card",
            sorry:"Sorry, this feature is currently unavailable. Please check back later.",
            fillCont:"Please fill in the blanks before paying. Your information will be kept confidential."

        },
        ar:{
            select:'اختر باقة',
            ends:'ينتهي العرض في #',
            one:'One-off',
            payment:'اختر طريقة دفع',
            contact:'يرجى التواصل معنا إذا كان لديك أي استفسارات',
            customer:'خدمة العملاء',
            days:"مجانا %d أيام VIP",
            month:"شهر %d مجاني VIP",
            months:"مجانا %d أشهر VIP",
            number:"أدخل رقم البطاقة",
            card:"رقم البطاقة",
            pay:"دفع # @",
            selectCard:"اختر بطاقة",
            addCard:"أضف بطاقة جديدة",
            sorry:"عذراً، هذه الميزة غير متوفر في الوقت الحالي. الرجاء التحقق مرة أخرى لاحقاً.",
            fillCont:"يُرجى ملء الفراغات قبل الدفع. سيتم الحفاظ على سرية معلوماتك."

        },
        tr:{
            select:'Bir paket seçin',
            ends:"#'de sona eriyor",
            one:'One-off',
            payment:'Bir ödeme yöntemi seçin',
            contact:'Sorularınız için bizimle iletişime geçin',
            customer:'Müşteri hizmetleri',
            days:"Ücretsiz %d Gün VIP",
            month:"Ücretsiz %d ay VIP",
            months:"Ücretsiz %d ay VIP",
            number:"Kart numarasını gir",
            card:"Kart numarası",
            pay:"# @ ÖDE",
            selectCard:"Bir kart seç",
            addCard:"Yeni kart ekle",
            sorry:"Üzgünüz, bu özellik şu anda kullanılamıyor. Lütfen daha sonra tekrar kontrol edin.",
            fillCont:"Lütfen ödeme öncesinde boşlukları doldurunuz. Bilgileriniz gizli tutulacaktır."
        },
        es:{
            select:'Seleccione un paquete',
            ends:'Termina a las #',
            one:'One-off',
            payment:'Seleccione un método de pago',
            contact:'Póngase en contacto con nosotros si tiene alguna pregunta',
            customer:'Servicio de atención al cliente',
            days:"%d días de VIP",
            month:"%d mes de VIP gratis",
            months:"%d meses de VIP gratis",
            number:"Introduzca el número de tarjeta",
            card:"Número de tarjeta",
            pay:"PAGAR # @",
            selectCard:"Seleccione una tarjeta",
            addCard:"Agregar nueva tarjeta",
            sorry:"Lo sentimos, esta función no está disponible actualmente. Vuelva a comprobar si está disponible más tarde.",
            fillCont:"Complete los espacios en blanco antes de pagar. Su información tendrá carácter confidencial."
        },
        in:{
            select:'Pilih paket',
            ends:'Berakhir pada #',
            one:'One-off',
            payment:'Pilih cara pembayaran',
            contact:'Hubungi kami jika ada pertanyaan',
            customer:'Layanan Pelanggan',
            days:"Gratis VIP %d Hari",
            month:"Gratis VIP %d Bulan",
            months:"Gratis VIP %d Bulan",
            number:"Masukkan nomor kartu",
            card:"Nomor kartu",
            pay:"BAYAR # @",
            selectCard:"Pilih kartu",
            addCard:"Tambah kartu baru",
            sorry:"Maaf, fitur ini tidak tersedia untuk saat ini. Silakan periksa kembali nanti.",
            fillCont:"Harap isi bagian yang kosong sebelum membayar. Informasi Anda akan dijaga kerahasiaannya."
        },
        id:{
            select:'Pilih paket',
            ends:'Berakhir pada #',
            one:'One-off',
            payment:'Pilih cara pembayaran',
            contact:'Hubungi kami jika ada pertanyaan',
            customer:'Layanan Pelanggan',
            days:"Gratis VIP %d Hari",
            month:"Gratis VIP %d Bulan",
            months:"Gratis VIP %d Bulan",
            number:"Masukkan nomor kartu",
            card:"Nomor kartu",
            pay:"BAYAR # @",
            selectCard:"Pilih kartu",
            addCard:"Tambah kartu baru",
            sorry:"Maaf, fitur ini tidak tersedia untuk saat ini. Silakan periksa kembali nanti.",
            fillCont:"Harap isi bagian yang kosong sebelum membayar. Informasi Anda akan dijaga kerahasiaannya."
        },
        hi:{
            select:'एक पैकेज चुनें',
            ends:'# में समाप्त होता है ',
            one:'एक बार ',
            payment:'कोई भुगतान विधि चुनें',
            contact:'अगर आपके पास कोई सवाल है तो हमसे संपर्क करें',
            customer:'ग्राहक सेवा',
            days:"निशुल्क %d दिनों हेतु VIP",
            month:"निशुल्क %d महीने हेतु VIP",
            months:"निशुल्क %d महीने हेतु VIP",
            number:"कार्ड नंबर दर्ज करें",
            card:"कार्ड नंबर",
            pay:"# @ का भुगतान करें",
            selectCard:"एक कार्ड का चयन करें",
            addCard:"नया कार्ड जोड़ें",
            sorry:"क्षमा करें, यह सुविधा वर्तमान में उपलब्ध नहीं है। कृपया फिर से बाद में चेक करें।",
            fillCont:"कृपया भुगतान करने से पहले रिक्त स्थान भरें। आपकी जानकारी गोपनीय रखी जाएगी।"
        },
        de:{
            select:'Wählen Sie ein Paket',
            ends:'Endet in #',
            one:'Einmalig',
            payment:'Wählen Sie eine Zahlungsart',
            contact:'Kontaktieren Sie uns, wenn Sie Fragen haben',
            customer:'Kundendienst',
            days:"Free %d Days VIP",
            month:"Free %d Month VIP",
            months:"Free %d Months VIP",
            number:"Kartennummer eingeben",
            card:"Kartennummer",
            pay:"# @ BEZAHLEN",
            selectCard:"Karte auswählen",
            addCard:"Neue Karte hinzufügen",
            sorry:"Entschuldigung, diese Funktion steht aktuell nicht zur Verfügung. Bitte versuchen Sie es später noch einmal.",
            fillCont:"Bitte tragen Sie die fehlenden Informationen ein, bevor Sie zahlen. Ihr Daten werden vertraulich behandelt."
        },
        fr:{
            select:'Sélectionnez un forfait',
            ends:'Se termine dans #',
            one:'Unique',
            payment:'Choisissez un moyen de paiement',
            contact:'Contactez nous si vous avez des questions',
            customer:'Service Clients',
            days:"%d jours VIP gratuits",
            month:"%d mois VIP gratuit",
            months:"%d mois VIP gratuits",
            number:"Saisir le numéro de carte",
            card:"Numéro de carte",
            pay:"PAYER # @",
            selectCard:"Sélectionner une carte",
            addCard:"Ajouter une nouvelle carte",
            sorry:"Désolé, cette fonctionnalité n'est pas disponible pour le moment. Veuillez revenir plus tard.",
            fillCont:"Veuillez remplir les champs avant de payer. Vos coordonnées resteront confidentielles."
           
        },
        ja:{
            select:'パッケージをお選びください',
            ends:'#で終了します',
            one:'1回限り',
            payment:'お支払い方法をお選びください',
            contact:'ご不明な点がございましたら、お問い合わせください。',
            customer:'カスタマーサービス',
            days:"%d日間無料VIP",
            month:"%dヶ月無料VIP",
            months:"%dヶ月無料VIP",
            number:"カード番号を入力",
            card:"カード番号",
            pay:"# @を支払う",
            selectCard:"カードを選択",
            addCard:"新しいカードを追加",
            sorry:"申し訳ありませんが、この機能は現在ご利用になれません。後で再度ご確認ください。",
            fillCont:"お支払い前に空欄にご入力ください。お客様の情報は極秘に扱われます。"
        },
        zh:{
            select:'選擇套裝方案',
            ends:'剩餘時間 #',
            one:'僅此一次',
            payment:'選擇付款方式',
            contact:'如有任何問題請聯絡我們',
            customer:'客戶服務',
            days:"免費%d天VIP",
            month:"免費%d月VIP",
            months:"免費%d月VIP",
            number:"輸入卡號",
            card:"卡號",
            pay:"支付 # @",
            selectCard:"選擇卡片",
            addCard:"新增卡片",
            sorry:"很抱歉，此功能目前無法使用。請稍後再返回查看~",
            fillCont:"請於付款前填寫欄位，您的資料將經保密處理。"
        },
        ko:{
            select:'패키지를 선택하세요',
            ends:'#에 종료됩니다',
            one:'일회성',
            payment:'결제 수단을 선택하세요',
            contact:'질문이 있을 경우 저희에게 연락해 주세요',
            customer:'고객 서비스',
            days:"무료 %d일 VIP",
            month:"무료 %d개월 VIP",
            months:"무료 %d개월 VIP",
            number:"카드 번호 입력",
            card:"카드 번호",
            pay:"# @ 결제",
            selectCard:"카드 선택",
            addCard:"새로운 카드 추가",
            sorry:"죄송합니다. 이 기능은 현재 사용할 수 없습니다. 나중에 다시 확인하세요.",
            fillCont:"결제 전에 공란을 작성해 주시기 바랍니다. 귀하의 정보는 안전하게 비밀로 보관됩니다."

        }
}
export default data;